# ********RoostGPT********

# Test generated by RoostGPT for test tr-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=48e4dd6cd8
# 
# 

# ********RoostGPT********
Feature: Employee API Tests

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { 'Accept': 'application/json' }

  Scenario Outline: Search employees with query parameter 'searchString'
    Given path 'employees'
    And param searchString = <searchString>
    When method GET
    Then status 200
    And match response == #[]
    And match each response[*].id == '#uuid'
    And match each response[*].jobTitle == '##string'
    And match each response[*].name == '##string'
    And match each response[*].email == '##string'

    Examples:
      | read('employees_get.csv') |

  Scenario: Search employees without 'searchString' query parameter
    Given path 'employees'
    When method GET
    Then status 200
    And match response == #[]
    And match each response[*].id == '#uuid'
    And match each response[*].jobTitle == '##string'
    And match each response[*].name == '##string'
    And match each response[*].email == '##string'

  Scenario: Search employees with invalid 'searchString' query parameter
    Given path 'employees'
    And param searchString = '$INVALID_QUERY$'
    When method GET
    Then status 400
    And match response.error ==
      """
      {
        "code": "#number",
        "message": "#string"
      }
      """
