# ********RoostGPT********

# Test generated by RoostGPT for test tr-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=48e4dd6cd8
# 
# 

# ********RoostGPT********
Feature: Employee API Tests

  Background:
    """
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { 'Accept': 'application/json' }
    """

  Scenario Outline: Search employees with query parameter `searchString`
    Given path 'employees'
    And param searchString = 
      """
      <searchString>
      """
    When method GET
    Then status 200
    And match response == 
      """
      []
      """

    Examples:
      | searchString                  |
      | ['John']                      |
      | ['Doe']                       |
      | ['John', 'Doe', 'Smith']      |
