# ********RoostGPT********

# Test generated by RoostGPT for test tr-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
Feature: Employee API

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Retrieve an employee by ID with valid ID
    Given path 'employees/<id>'
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'
    And match response.email == '#regex ^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$'

    Examples:
      | read('employees_id_get.csv') |

  Scenario Outline: Retrieve an employee with non-existent ID
    Given path 'employees/<id>'
    When method GET
    Then status 404
    And match response == null

    Examples:
      | id                                     |
      | '00000000-0000-0000-0000-000000000000' |
      | 'ffffffff-ffff-ffff-ffff-ffffffffffff' |

  Scenario Outline: Retrieve an employee with invalid ID format
    Given path 'employees/<id>'
    When method GET
    Then status != 200
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | id        |
      | 'invalid' |
      | '123456'  |
