# ********RoostGPT********

# Test generated by RoostGPT for test tr-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=e5b9d8d67f
# 
# 

# ********RoostGPT********
Feature: Employee API Tests

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def headers = { 'Accept': 'application/json' }
    * configure headers = headers

  Scenario Outline: Adding a new employee with valid input
    Given path 'employees'
    And request
      """
      {
        "id": "<id>",
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
      """
    When method POST
    Then status 201
    And match response.id == '#string'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'

    Examples:
      | read('employees_post.csv') |

  Scenario Outline: Invalid input when adding employee
    Given path 'employees'
    And request
      """
      {
        "id": "<id>",
        "jobTitle": "<jobTitle>",
        "name": "",
        "email": "<email>"
      }
      """
    When method POST
    Then status 400
    And match response.error.message == '#string'
    And match response.error.code == '#string'

    Examples:
      | id                                       | jobTitle           | email             |
      | ['d290f1ee-6c54-4b01-90e6-d701748f0851'] | ['System Analyst'] | ['invalid_email'] |

  Scenario Outline: Adding employee that already exists
    Given path 'employees'
    And request
      """
      {
        "id": "<id>",
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
      """
    When method POST
    Then status 409
    And match response.error.message == '#string'
    And match response.error.code == '#string'

    Examples:
      | id                                       | jobTitle           | name           | email                        |
      | ['d290f1ee-6c54-4b01-90e6-d701748f0851'] | ['System Analyst'] | ['John Smith'] | ['john.smith@acme-corp.com'] |

  Scenario: Validating response headers for successful employee creation
    Given path 'employees'
    And request
      """
      {
        "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
        "jobTitle": "System Analyst",
        "name": "John Smith",
        "email": "john.smith@acme-corp.com"
      }
      """
    When method POST
    Then status 201
    And match responseHeaders['Content-Type'] == '#contains application/json'
