# ********RoostGPT********

# Test generated by RoostGPT for test tr-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
Feature: Employee API

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Retrieve an employee by ID with valid ID
    Given path 'employees/<id>'
    When method GET
    Then status 200
    """
    {
      "id": "#string",
      "id": "#regex [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
      "jobTitle": "#string",
      "name": "#string",
      "email": "#string",
      "email": "#regex ^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}"
    }
    """
    Examples:
      | id                                   |
      | ['123e4567-e89b-12d3-a456-426655440000'] |
      | ['ab23cdef-ab12-34cd-ef56-7890ghijklmn'] |

  Scenario: Retrieve an employee list
    Given path 'employees'
    When method GET
    Then status 200
    """
    [
      {
        "id": "#string",
        "id": "#regex [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        "jobTitle": "#string",
        "name": "#string",
        "email": "#string",
        "email": "#regex ^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}"
      }
    ]
    """

  Scenario: Create a new employee
    Given path 'employees'
    And request """
    {
      "jobTitle": "Software Engineer",
      "name": "John Doe",
      "email": "johndoe@example.com"
    }
    """
    When method POST
    Then status 201
    """
    {
      "id": "#string",
      "id": "#regex [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
      "jobTitle": "Software Engineer",
      "name": "John Doe",
      "email": "johndoe@example.com"
    }
    """

  Scenario Outline: Delete an employee by ID
    Given path 'employees/<id>'
    When method DELETE
    Then status 204
    Examples:
      | id                                   |
      | ['123e4567-e89b-12d3-a456-426655440000'] |
      | ['ab23cdef-ab12-34cd-ef56-7890ghijklmn'] |
