# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=b53eb88d3b
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Cancel Product Order By Id
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
        "order": {
          "associatedDocument": "<associatedDocument>",
          "customer": {
            "subscriberId": "<subscriberId>"
          }
        }
      }
      """
    When method POST
    Then status <statusCode>
    And match response == '#object'
    And match response.control == '#object'
    And match response.control.type == '#string'
    And match response.control.type == '#? _.length == 1'
    And match response.control.code == '#string'
    And match response.control.code == '#? _.length == 3'
    And match response.control.message == '#string'

    Examples:
      | orderId        | associatedDocument | subscriberId | statusCode |
      | 20230315000001 | VTT001             | SVTAL001     |        200 |
      | 20230315000002 | VTT002             | SVTAL002     |        400 |
      | 20230315000003 | VTT003             | SVTAL003     |        401 |
      | 20230315000004 | VTT004             | SVTAL004     |        403 |
      | 20230315000005 | VTT005             | SVTAL005     |        404 |
      | 20230315000006 | VTT006             | SVTAL006     |        406 |
      | 20230315000007 | VTT007             | SVTAL007     |        423 |
      | 20230315000008 | VTT008             | SVTAL008     |        429 |
      | 20230315000009 | VTT009             | SVTAL009     |        500 |
      | 20230315000010 | VTT010             | SVTAL010     |        503 |
      | 20230315000011 | VTT011             | SVTAL011     |        504 |

  Scenario: Cancel Product Order By Id - Validate Response Schema
    Given path '/cancelProductOrder/20230315000001'
    And request
      """
      {
        "order": {
          "associatedDocument": "VTT001",
          "customer": {
            "subscriberId": "SVTAL001"
          }
        }
      }
      """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.control == '#object'
    And match response.control.type == '#string'
    And match response.control.type == '#? _.length == 1'
    And match response.control.code == '#string'
    And match response.control.code == '#? _.length == 3'
    And match response.control.message == '#string'

  Scenario: Cancel Product Order By Id - Validate Path Parameter
    Given path '/cancelProductOrder/20230315000001'
    And request
      """
      {
        "order": {
          "associatedDocument": "VTT001",
          "customer": {
            "subscriberId": "SVTAL001"
          }
        }
      }
      """
    When method POST
    Then status 200
    And match response.path == 'cancelProductOrder/20230315000001'

  Scenario: Cancel Product Order By Id - Validate Request Body Schema
    Given path '/cancelProductOrder/20230315000001'
    And request
      """
      {
        "order": {
          "associatedDocument": "VTT001",
          "customer": {
            "subscriberId": "SVTAL001"
          }
        }
      }
      """
    When method POST
    Then status 200
    And match request.order == '#object'
    And match request.order.associatedDocument == '#string'
    And match request.order.associatedDocument == '#? _.length <= 30'
    And match request.order.customer == '#object'
    And match request.order.customer.subscriberId == '#string'
    And match request.order.customer.subscriberId == '#? _.length <= 30'
