# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=99e96e3191
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Send Product Order Information Required Event
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "id": '<orderId>',
            "correlationOrder": '<correlationOrder>',
            "associatedDocument": '<associatedDocument>',
            "issue": {
              "code": '<issueCode>',
              "description": '<issueDescription>',
              "type": '<issueType>',
              "observation": '<observation>',
              "updateDate": '<updateDate>',
              "action": '<action>',
              "task": '<task>',
              "fieldActivity": <fieldActivity>,
              "reason": '<reason>'
            }
          }
        }
      }
      """
    When method POST
    Then status 204
    And match responseHeaders['Content-Type'] contains 'application/json'
    And match response == ''

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |

  Scenario: Attempt to send invalid Product Order Information Required Event
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      {
        "invalidField": "invalidValue"
      }
      """
    When method POST
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Attempt to send Product Order Information Required Event without authorization
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = null
    And request
      """
      {
        "notification": {
          "order": {
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 401
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Attempt to send Product Order Information Required Event when server is unavailable
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 503
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Attempt to send Product Order Information Required Event with server timeout
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 504
    And match response == '#object'
    And match response.message == '#string'
