# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=999efa10b6
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Cancel Product Order Create Event - Successful
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": '<associatedDocument>',
            "id": '<id>'
          }
        }
      }
      """
    When method POST
    Then status 204
    And match responseHeaders['Content-Type'][0] == 'application/json'

    Examples:
      | read('listener_cancelProductOrderCreateEvent_post.csv') |

  Scenario: Cancel Product Order Create Event - Bad Request
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "",
            "id": ""
          }
        }
      }
      """
    When method POST
    Then status 400

  Scenario: Cancel Product Order Create Event - Unauthorized
    Given path '/listener/cancelProductOrderCreateEvent'
    And configure headers = null
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "VTT001",
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 401

  Scenario: Cancel Product Order Create Event - Server Error
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "ERROR",
            "id": "ERROR"
          }
        }
      }
      """
    When method POST
    Then status 500

  Scenario: Cancel Product Order Create Event - Service Unavailable
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "UNAVAILABLE",
            "id": "UNAVAILABLE"
          }
        }
      }
      """
    When method POST
    Then status 503

  Scenario: Cancel Product Order Create Event - Timeout
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "TIMEOUT",
            "id": "TIMEOUT"
          }
        }
      }
      """
    When method POST
    Then status 504
