# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /listener/productOrderStateChangeEvent_post for http method type POST 
# RoostTestHash=2a8518ba6f
# 
# 

# ********RoostGPT********
Feature: State Change Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Send state change event notification
    Given path '/listener/productOrderStateChangeEvent'
    And request
      """
      {
        "notification": {
          "date": '<date>',
          "customer": {
            "subscriberId": '<subscriberId>'
          },
          "order": {
            "id": '<orderId>',
            "correlationOrder": '<correlationOrder>',
            "associatedDocument": '<associatedDocument>',
            "type": '<type>',
            "code": '<code>',
            "description": '<description>',
            "lostEquipment": <lostEquipment>,
            "resource": {
              "gponAccess": '<gponAccess>',
              "devices": {
                "device": [
                  {
                    "category": '<category>',
                    "type": '<deviceType>',
                    "description": '<deviceDescription>',
                    "state": '<state>',
                    "usageState": '<usageState>',
                    "startOperatingDate": '<startOperatingDate>',
                    "resourceCharacteristic": [
                      {
                        "name": '<characteristicName>',
                        "value": '<characteristicValue>'
                      }
                    ]
                  }
                ]
              },
              "fiberPath": {
                "items": {
                  "item": [
                    {
                      "name": '<itemName>',
                      "value": '<itemValue>'
                    }
                  ]
                }
              }
            }
          }
        }
      }
      """
    When method POST
    Then status 204
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response == ''

    Examples:
      | read('listener_productOrderStateChangeEvent_post.csv') |

  Scenario: Validate error response - 400 Bad Request
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 400
    And match response == '#object'

  Scenario: Validate error response - 401 Unauthorized
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 401
    And match response == '#object'

  Scenario: Validate error response - 500 Internal Server Error
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 500
    And match response == '#object'

  Scenario: Validate error response - 503 Service Unavailable
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 503
    And match response == '#object'

  Scenario: Validate error response - 504 Gateway Timeout
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 504
    And match response == '#object'
