# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=10f12a7f6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Create Product Order Event
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": '<date>',
          "order": {
            "id": '<id>',
            "associatedDocument": '<associatedDocument>',
            "correlationOrder": '<correlationOrder>'
          }
        }
      }
      """
    When method POST
    Then status 204
    And match responseHeaders contains { 'Content-Type': '#present' }
    And assert responseTime < 5000

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario: Create Product Order Event with Invalid Data
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "invalid-date",
          "order": {
            "id": "",
            "associatedDocument": "",
            "correlationOrder": ""
          }
        }
      }
      """
    When method POST
    Then status 400
    And match response contains { message: '#present' }

  Scenario: Create Product Order Event with Unauthorized Access
    * configure headers = null
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-07-15T10:30:00-03:00",
          "order": {
            "id": "20230715000002",
            "associatedDocument": "VTT002",
            "correlationOrder": "11"
          }
        }
      }
      """
    When method POST
    Then status 401
    And match response contains { message: '#present' }

  Scenario: Create Product Order Event with Server Error
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-07-15T10:30:00-03:00",
          "order": {
            "id": "20230715000002",
            "associatedDocument": "VTT002",
            "correlationOrder": "11"
          }
        }
      }
      """
    When method POST
    Then status 500
    And match response contains { message: '#present' }

  Scenario: Create Product Order Event with Service Unavailable
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-07-15T10:30:00-03:00",
          "order": {
            "id": "20230715000002",
            "associatedDocument": "VTT002",
            "correlationOrder": "11"
          }
        }
      }
      """
    When method POST
    Then status 503
    And match response contains { message: '#present' }

  Scenario: Create Product Order Event with Timeout
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-07-15T10:30:00-03:00",
          "order": {
            "id": "20230715000002",
            "associatedDocument": "VTT002",
            "correlationOrder": "11"
          }
        }
      }
      """
    When method POST
    Then status 504
    And match response contains { message: '#present' }
