# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=94e2304cc2
# 
# 

# ********RoostGPT********
Feature: Product Order API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Create a product order successfully
    Given path '/productOrder'
    And header x-request-id = '<x-request-id>'
    And header x-service-host = '<x-service-host>'
    When method post
    Then status 201
    And match response == '#object'
    And match response.control == '#object'
    And match response.control.type == '#string'
    And match response.control.message == '#object'
    And match response.control.message.Yash == '#string'
    And match response.control.code == '#string'
    And match response.order == '#object'
    And match response.order.id == '#string'

    Examples:
      | read('productOrder_post.csv') |

  Scenario Outline: Create a product order with error responses
    Given path '/productOrder'
    And header x-request-id = '<x-request-id>'
    And header x-service-host = '<x-service-host>'
    When method post
    Then status <status_code>
    And match response.type == '#string'
    And match response.message == '#object'
    And match response.message.Yash == '#string'
    And match response.code == '#string'

    Examples:
      | x-request-id | x-service-host  | status_code |
      | req-003      | service-host-3  |         400 |
      | req-004      | service-host-4  |         401 |
      | req-005      | service-host-5  |         403 |
      | req-006      | service-host-6  |         404 |
      | req-007      | service-host-7  |         406 |
      | req-008      | service-host-8  |         429 |
      | req-009      | service-host-9  |         500 |
      | req-010      | service-host-10 |         503 |
      | req-011      | service-host-11 |         504 |
