# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test generated by RoostGPT for test test-karate-with-BR using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=7a88529866
# 
# 

# ********RoostGPT********
Feature: Test PATCH /productOrder/{order.Id} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: PATCH /productOrder/{order.Id} with valid input
    Given path 'productOrder', '<orderId>'
    And request
      """
      {
        "order": {
          "correlationOrder": "<correlationOrder>",
          "associatedDocument": "<associatedDocument>",
          "associatedDocumentDate": "<associatedDocumentDate>",
          "type": "<type>",
          "infraType": "<infraType>",
          "orderItem": <orderItem>,
          "task": {
            "description": "<taskDescription>",
            "updateDate": "<taskUpdateDate>",
            "action": "<taskAction>"
          }
        }
      }
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.message == '#object'
    And match response.message.Yash == '#string'
    And match response.code == '#string'

    Examples:
      | read('productOrder_order.Id_patch.csv') |

  Scenario Outline: PATCH /productOrder/{order.Id} with invalid input - Bad Request
    Given path 'productOrder', '<orderId>'
    And request
      """
      {
        "order": {
          "correlationOrder": "<correlationOrder>",
          "associatedDocument": "<associatedDocument>",
          "associatedDocumentDate": "<associatedDocumentDate>",
          "type": "<type>",
          "infraType": "<infraType>",
          "orderItem": <orderItem>,
          "task": {
            "description": "<taskDescription>",
            "updateDate": "<taskUpdateDate>",
            "action": "<taskAction>"
          }
        }
      }
      """
    When method PATCH
    Then status 400
    And match response == '#object'
    And match response.message == '#object'
    And match response.message.Yash == '#string'
    And match response.code == '#string'

    Examples:
      | orderId | correlationOrder | associatedDocument | associatedDocumentDate | type  | infraType | orderItem | taskDescription | taskUpdateDate       | taskAction |
      | order3  | CO003            | AD003              | invalid-date           | Type3 | Infra3    | []        | Task 3          | 2023-05-05T16:45:00Z | Action3    |

  Scenario: PATCH /productOrder/{order.Id} with non-existent order ID
    Given path 'productOrder', 'non-existent-order'
    And request
      """
      {
        "order": {
          "correlationOrder": "CO999",
          "associatedDocument": "AD999",
          "associatedDocumentDate": "2023-05-10T08:00:00Z",
          "type": "Type999",
          "infraType": "Infra999",
          "orderItem": [],
          "task": {
            "description": "Task 999",
            "updateDate": "2023-05-11T10:30:00Z",
            "action": "Action999"
          }
        }
      }
      """
    When method PATCH
    Then status 404
    And match response == '#object'
    And match response.message == '#object'
    And match response.message.Yash == '#string'
    And match response.code == '#string'

  Scenario: PATCH /productOrder/{order.Id} with server error
    Given path 'productOrder', 'server-error-order'
    And request
      """
      {
        "order": {
          "correlationOrder": "CO500",
          "associatedDocument": "AD500",
          "associatedDocumentDate": "2023-05-15T13:00:00Z",
          "type": "Type500",
          "infraType": "Infra500",
          "orderItem": [],
          "task": {
            "description": "Task 500",
            "updateDate": "2023-05-16T14:45:00Z",
            "action": "Action500"
          }
        }
      }
      """
    When method PATCH
    Then status 500
    And match response == '#object'
    And match response.message == '#object'
    And match response.message.Yash == '#string'
    And match response.code == '#string'
