# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
"""
Pytest test suite for API endpoint testing.

To execute this test suite, use the following command:
pytest -v
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

_ENDPOINT = "/v1/current.json"
_METHOD = "get"
_TEST_DATA_FILE = "endpoint_test_data.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE

@pytest.fixture(scope="module")
def swagger_validator():
    spec_path = _here / "api.json"
    return SwaggerSchemaValidator(str(spec_path))

@pytest.mark.smoke
def test_realtime_weather_success(api_client, swagger_validator, merged_test_data):
    data = merged_test_data(_endpoint_data_path)
    for test_case in data:
        params = {"q": test_case['q']}
        if 'lang' in test_case:
            params['lang'] = test_case['lang']
        
        response = api_client.get(_ENDPOINT, params=params)
        
        assert response.status_code == test_case['statusCode'], f"Unexpected status code: {response.status_code}"
        
        validation_result = swagger_validator.validate_schema_by_response(_ENDPOINT, _METHOD, str(response.status_code), response)

        assert validation_result['valid'], f"Response validation failed: {validation_result.get('message', '')}"

def test_realtime_weather_invalid_auth(api_client, swagger_validator):
    headers = {"Authorization": "InvalidToken"}
    response = api_client.get(_ENDPOINT, headers=headers, params={"q": "London"})

    assert response.status_code == 401, f"Expected 401 Unauthorized, got {response.status_code}"

    validation_result = swagger_validator.validate_schema_by_response(_ENDPOINT, _METHOD, "401", response)
    assert validation_result['valid'], f"Response validation failed: {validation_result.get('message', '')}"

def test_realtime_weather_missing_auth(api_client, swagger_validator):
    response = api_client.get(_ENDPOINT, params={"q": "London"})

    assert response.status_code == 401, f"Expected 401 Unauthorized, got {response.status_code}"

    validation_result = swagger_validator.validate_schema_by_response(_ENDPOINT, _METHOD, "401", response)
    assert validation_result['valid'], f"Response validation failed: {validation_result.get('message', '')}"

def test_realtime_weather_missing_required_param(api_client, swagger_validator):
    response = api_client.get(_ENDPOINT)

    assert response.status_code == 400, f"Expected 400 Bad Request, got {response.status_code}"

    validation_result = swagger_validator.validate_schema_by_response(_ENDPOINT, _METHOD, "400", response)
    assert validation_result['valid'], f"Response validation failed: {validation_result.get('message', '')}"
