# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
"""
Test suite for the Weather API using pytest.

This test suite covers the /v1/current.json endpoint, testing various scenarios
including successful responses, client errors, and server errors. The tests
utilize fixtures defined in conftest.py for configuration management and API
client setup.

Instructions for running the tests:
- Ensure pytest is installed in your environment.
- Set the necessary environment variables for API host and key.
- Execute the tests using the command: pytest test_weather_api.py
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Load the API specification
_API_SPEC_PATH = Path(__file__).parent / "api.json"
validator = SwaggerSchemaValidator(str(_API_SPEC_PATH))

# Load test data from JSON file
_TEST_DATA_FILENAME = "current_json.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILENAME

def _load_json_file(file_path):
    with open(file_path, "r") as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"{case['scenario']}-{case['q']}" for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_current_weather_success(api_client, scenario_case, config_test_data):
    """
    Test the /v1/current.json endpoint for successful response scenarios.
    """
    # Merge scenario-specific data with default test data
    test_data = {**config_test_data, **scenario_case}
    
    # Prepare request parameters
    params = {'q': test_data['q']}
    if 'lang' in test_data:
        params['lang'] = test_data['lang']

    # Execute API request
    response = api_client.get("v1/current.json", params=params)

    # Validate response status code
    assert response.status_code == test_data['statusCode'], (
        f"Expected {test_data['statusCode']}, got {response.status_code}"
    )

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        endpoint="/v1/current.json",
        method="GET",
        status_code=str(test_data['statusCode']),
        response=response
    )
    assert validation_result['valid'], validation_result.get('message', '')

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_current_weather_invalid_key(api_client, scenario_case, config_test_data):
    """
    Test the /v1/current.json endpoint with an invalid API key.
    """
    # Prepare request parameters
    test_data = {**config_test_data, **scenario_case}
    params = {'q': test_data['q']}
    if 'lang' in test_data:
        params['lang'] = test_data['lang']

    # Use a hardcoded invalid API key
    api_client.auth = "InvalidApiKey"

    # Execute API request
    response = api_client.get("v1/current.json", params=params)

    # Validate response status code
    assert response.status_code == 401, (
        f"Expected 401, got {response.status_code}"
    )

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        endpoint="/v1/current.json",
        method="GET",
        status_code="401",
        response=response
    )
    assert validation_result['valid'], validation_result.get('message', '')

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_current_weather_missing_key(api_client, scenario_case, config_test_data):
    """
    Test the /v1/current.json endpoint without an API key.
    """
    # Prepare request parameters
    test_data = {**config_test_data, **scenario_case}
    params = {'q': test_data['q']}
    if 'lang' in test_data:
        params['lang'] = test_data['lang']

    # Remove API key
    api_client.auth = None

    # Execute API request
    response = api_client.get("v1/current.json", params=params)

    # Validate response status code
    assert response.status_code == 401, (
        f"Expected 401, got {response.status_code}"
    )

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        endpoint="/v1/current.json",
        method="GET",
        status_code="401",
        response=response
    )
    assert validation_result['valid'], validation_result.get('message', '')

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_current_weather_invalid_params(api_client, scenario_case, config_test_data):
    """
    Test the /v1/current.json endpoint with invalid query parameters.
    """
    # Prepare request parameters
    test_data = {**config_test_data, **scenario_case}
    params = {'q': "InvalidLocation"}

    # Execute API request
    response = api_client.get("v1/current.json", params=params)

    # Validate response status code
    assert response.status_code == 400, (
        f"Expected 400, got {response.status_code}"
    )

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        endpoint="/v1/current.json",
        method="GET",
        status_code="400",
        response=response
    )
    assert validation_result['valid'], validation_result.get('message', '')
