# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
"""
Instructions:
- Ensure you have pytest installed: `pip install pytest`
- Place the `conftest.py`, `validator.py`, and `config.yml` in the same directory as this file.
- Run the tests using the command: `pytest <this_filename>.py`
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Constants
TEST_DATA_FILENAME = "ip_json.json"
API_SPEC_PATH = "api.json"
ENDPOINT = "/v1/ip.json"

# Load test data from JSON file
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(path):
    with open(path, 'r') as file:
        return json.load(file)

_ENDPOINT_TEST_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_TEST_DATA
_PARAM_IDS = [f"{case['scenario']}" for case in _ENDPOINT_TEST_DATA]

# Initialize Swagger Schema Validator
validator = SwaggerSchemaValidator(API_SPEC_PATH)

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_ip_lookup_success(api_client, scenario_case, config_test_data):
    """
    Test successful IP lookup scenarios.
    """
    params = {'q': scenario_case['q']}
    response = api_client.get(ENDPOINT, params=params)
    
    # Validate response status code
    assert response.status_code == scenario_case['statusCode']

    # Validate response schema
    validation_result = validator.validate_schema_by_response(ENDPOINT, 'GET', str(scenario_case['statusCode']), response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_ip_lookup_error(api_client, scenario_case, config_test_data):
    """
    Test error scenarios for IP lookup.
    """
    params = {'q': scenario_case['q']}
    response = api_client.get(ENDPOINT, params=params)
    
    if scenario_case['statusCode'] != 200:
        # Validate response status code
        assert response.status_code == scenario_case['statusCode']

        # Validate response schema
        validation_result = validator.validate_schema_by_response(ENDPOINT, 'GET', str(scenario_case['statusCode']), response)
        assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"
