# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
"""
Pytest Test Suite for Astronomy API

This test suite uses pytest to test the Astronomy API as defined in the OpenAPI specification.
The tests verify correct behavior for different endpoints, methods, and response codes.
The tests are parameterized with data from the astronomy_json.json file.
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator
import json

# Load the OpenAPI spec for validation
spec_path = Path(__file__).parent / "api.json"
swagger_validator = SwaggerSchemaValidator(str(spec_path))

# Load the test data from the JSON file
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / "astronomy_json.json"
with open(_endpoint_data_path, "r") as f:
    _ENDPOINT_DATA = json.load(f)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case["scenario"] for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_astronomy_api(api_client, host, config_test_data, scenario_case):
    """
    Test the /v1/astronomy.json endpoint with various scenarios.

    The test uses parameterized inputs from the JSON file and validates the response schema
    using the SwaggerSchemaValidator.
    """
    endpoint = "v1/astronomy.json"
    params = {
        "q": scenario_case.get("q", config_test_data.get("q")),
        "dt": scenario_case.get("dt", config_test_data.get("dt")),
    }

    # Validate request before sending
    request_validation = swagger_validator.validate_json(params, "AstronomyRequestSchema")
    assert request_validation["valid"], f"Request validation failed: {request_validation['message']}"

    # Make the GET request
    response = api_client.get(endpoint, params=params)

    # Validate response schema
    response_validation = swagger_validator.validate_schema_by_response(
        f"/{endpoint}", "GET", str(scenario_case["statusCode"]), response
    )
    assert response_validation["valid"], f"Response validation failed: {response_validation['message']}"

    # Validate status code
    assert response.status_code == scenario_case["statusCode"], f"Unexpected status code: {response.status_code}"

    # Additional assertions based on status code
    if response.status_code == 200:
        # Validate specific fields in a successful response
        assert "location" in response.json(), "Location data missing in response"
        assert "astronomy" in response.json(), "Astronomy data missing in response"

    elif response.status_code == 400:
        assert "code" in response.json(), "Error code missing in response"
        assert "message" in response.json(), "Error message missing in response"

    elif response.status_code == 401:
        assert "code" in response.json(), "Error code missing in response"
        assert "message" in response.json(), "Error message missing in response"

    elif response.status_code == 403:
        assert "code" in response.json(), "Error code missing in response"
        assert "message" in response.json(), "Error message missing in response"

    # Print scenario for debugging
    print(f"Test scenario: {scenario_case['scenario']}")
