# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /forecast.json_get for http method type GET 
# RoostTestHash=462421f697
# 
# 

# ********RoostGPT********
"""
This module contains pytest tests for the Weather API's forecast endpoint.
Ensure you have the forecast_json.json file in the same directory as this test file.
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load the OpenAPI schema for validation
api_spec_path = Path(__file__).parent / 'api.json'
schema_validator = SwaggerSchemaValidator(str(api_spec_path))

# Load test data from JSON file
def _load_json_file(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / 'forecast_json.json'
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case['scenario'] for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_forecast_api(api_client, host, auth, config_test_data, scenario_case):
    """
    Test various scenarios for the forecast API.
    """
    endpoint = 'forecast.json'
    params = {
        'q': scenario_case.get('q', config_test_data.get('q')),
        'days': scenario_case.get('days', config_test_data.get('days')),
    }
    if 'lang' in scenario_case:
        params['lang'] = scenario_case['lang']
    if 'alerts' in scenario_case:
        params['alerts'] = scenario_case['alerts']
    if 'aqi' in scenario_case:
        params['aqi'] = scenario_case['aqi']

    # Validate request params
    schema_validator.validate_json(params, 'ForecastParams')

    # Make the API request
    response = api_client.get(endpoint=endpoint, params=params)
    status_code = scenario_case['statusCode']

    # Assert the status code
    assert response.status_code == status_code, f"Expected {status_code}, got {response.status_code}"

    # Validate response schema
    validation_result = schema_validator.validate_schema_by_response(endpoint=f'/{endpoint}', method='GET', status_code=status_code, response=response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

# Additional tests for security schema would be placed here, but are skipped as per instructions.
