# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /marine.json_get for http method type GET 
# RoostTestHash=fb78c63880
# 
# 

# ********RoostGPT********
"""
Pytest suite for testing Marine Weather API

Endpoints:
- /v1/marine.json

Security Schemas:
- ApiKeyAuth

Instructions:
Ensure that the necessary environment variables are set for the API host and API key.
Use the conftest.py file to configure fixtures and validate requests and responses.
"""
import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Load the OpenAPI specification for validation
swagger_path = Path(__file__).parent / "api.json"
validator = SwaggerSchemaValidator(swagger_source=str(swagger_path))

# Load test data from JSON file
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / "marine_json.json"

def _load_json_file(path):
    with open(path, 'r') as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"Scenario: {data['scenario']}" for data in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_marine_weather_api(api_client, config_test_data, scenario_case):
    """
    Test the Marine Weather API endpoint with various scenarios.
    """
    endpoint = "marine.json"
    params = {**config_test_data, **scenario_case}
    
    # Validate request before sending
    validator.validate_json(params, "MarineWeatherRequest")

    # Make the API request
    response = api_client.get(endpoint=endpoint, params=params)
    
    # Validate response status code
    assert response.status_code == scenario_case['statusCode'], \
        f"Expected status code {scenario_case['statusCode']}, got {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        endpoint=f"/v1/{endpoint}",
        method="GET",
        status_code=str(response.status_code),
        response=response
    )
    assert validation_result["valid"], f"Response validation failed: {validation_result['message']}"

    # Additional checks for specific scenarios
    if scenario_case['statusCode'] == 200:
        assert "location" in response.json(), "Expected 'location' in response"
        assert "forecast" in response.json(), "Expected 'forecast' in response"

