# ********RoostGPT********

# Test generated by RoostGPT for test pytest-weather using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
"""
Pytest Test Suite for Weather API

This test suite validates the Weather API endpoints using pytest framework.
It covers various scenarios including successful responses, client errors,
and server errors. The tests are parameterized using data from a JSON file
and utilize fixtures for configuration and API client setup.

Instructions for running the tests:
1. Ensure pytest is installed in your environment.
2. Place the `conftest.py`, `validator.py`, and `config.yml` in the same directory.
3. Execute the tests using the command: pytest <test_file_name>.py
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load test data from JSON file
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / "current_json.json"
with open(_endpoint_data_path, 'r') as file:
    _ENDPOINT_DATA = json.load(file)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"Scenario: {case['scenario']}" for case in _ENDPOINT_DATA]

# Initialize SwaggerSchemaValidator
swagger_validator = SwaggerSchemaValidator(str(_here / "api.json"))

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_realtime_weather(api_client, config_test_data, scenario_case):
    """
    Test the /v1/current.json endpoint for various scenarios.
    """
    endpoint = "/v1/current.json"
    params = {
        "q": scenario_case.get("q"),
        "lang": scenario_case.get("lang", None)
    }
    
    # Remove None values from params
    params = {k: v for k, v in params.items() if v is not None}

    # Validate request parameters
    swagger_validator.validate_json(params, "realtime-weather")

    # Make API request
    response = api_client.get(endpoint, params=params)

    # Validate response status code
    assert response.status_code == scenario_case["statusCode"], f"Expected {scenario_case['statusCode']} but got {response.status_code}"

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, "GET", str(response.status_code), response)
    assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message', '')}"

    # Additional response content validation can be added here if needed

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_realtime_weather_invalid_auth(api_client, scenario_case):
    """
    Test the /v1/current.json endpoint with invalid authentication.
    """
    endpoint = "/v1/current.json"
    params = {
        "q": scenario_case.get("q"),
        "lang": scenario_case.get("lang", None)
    }
    
    # Remove None values from params
    params = {k: v for k, v in params.items() if v is not None}

    # Override auth headers with invalid token
    invalid_auth_headers = {"Authorization": "Bearer invalid_token"}

    # Make API request
    response = api_client.get(endpoint, params=params, headers=invalid_auth_headers)

    # Validate response status code for invalid auth
    assert response.status_code == 401, f"Expected 401 but got {response.status_code}"

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, "GET", "401", response)
    assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message', '')}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_realtime_weather_missing_auth(api_client, scenario_case):
    """
    Test the /v1/current.json endpoint with missing authentication.
    """
    endpoint = "/v1/current.json"
    params = {
        "q": scenario_case.get("q"),
        "lang": scenario_case.get("lang", None)
    }
    
    # Remove None values from params
    params = {k: v for k, v in params.items() if v is not None}

    # Make API request without auth headers
    response = api_client.get(endpoint, params=params, headers={})

    # Validate response status code for missing auth
    assert response.status_code == 401, f"Expected 401 but got {response.status_code}"

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, "GET", "401", response)
    assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message', '')}"
