# ********RoostGPT********

# Test generated by RoostGPT for test pytest-weather using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the Weather API.

This suite tests the /v1/current.json endpoint for various scenarios including
successful responses, client errors, and server errors. It uses parameterized
tests to iterate over test data defined in a JSON file.

Setup:
- Ensure the `config.yml` file is correctly configured with the API host and authentication details.
- Place the `current_json.json` file in the same directory as this test file.

Run the tests using pytest:
$ pytest test_weather_api.py
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load the OpenAPI specification for validation
validator = SwaggerSchemaValidator('api.json')

# Load test data from JSON file
ENDPOINT_TEST_DATA_PATH = Path(__file__).parent / 'current_json.json'
with open(ENDPOINT_TEST_DATA_PATH, 'r') as file:
    ENDPOINT_TEST_DATA = json.load(file)

@pytest.mark.parametrize("test_data", ENDPOINT_TEST_DATA)
def test_realtime_weather(api_client, config_test_data, test_data):
    """
    Test the /v1/current.json endpoint for various scenarios.

    Args:
        api_client: The API client fixture.
        config_test_data: The default test data from config.
        test_data: The scenario-specific test data from JSON.
    """
    # Merge default test data with scenario-specific data
    request_data = {**config_test_data, **test_data}

    # Prepare request parameters
    params = {
        "q": request_data.get("q"),
        "lang": request_data.get("lang", None)
    }

    # Validate request schema before sending
    validator.validate_json(params, 'RealtimeWeatherRequest')

    # Make the API request
    response = api_client.get('/v1/current.json', params=params)

    # Validate response status code
    assert response.status_code == request_data["statusCode"], f"Unexpected status code: {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        '/v1/current.json', 'GET', str(response.status_code), response
    )
    assert validation_result["valid"], f"Response schema validation failed: {validation_result.get('message')}"

    # Additional assertions based on scenario
    if response.status_code == 200:
        response_data = response.json()
        assert "location" in response_data, "Missing 'location' in response"
        assert "current" in response_data, "Missing 'current' in response"

@pytest.mark.parametrize("auth_key", [None, "invalid_key"])
def test_authentication_errors(api_client, auth_key):
    """
    Test authentication errors for the /v1/current.json endpoint.

    Args:
        api_client: The API client fixture.
        auth_key: The authentication key to use for the request.
    """
    # Prepare request parameters
    params = {"q": "New York"}

    # Override API client auth headers
    api_client.auth = {'Authorization': f"Bearer {auth_key}"} if auth_key else {}

    # Make the API request
    response = api_client.get('/v1/current.json', params=params)

    # Validate response status code
    assert response.status_code == 401, "Expected 401 Unauthorized"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        '/v1/current.json', 'GET', '401', response
    )
    assert validation_result["valid"], f"Response schema validation failed: {validation_result.get('message')}"
