# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
"""
Instructions for running the tests:
1. Ensure you have pytest and requests installed in your environment.
2. Set the environment variable WEATHER_API_API_HOST as needed.
3. Run the tests using the command: pytest <test_file_name>.py
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Load API spec for validation
API_SPEC_PATH = "api.json"
validator = SwaggerSchemaValidator(API_SPEC_PATH)

# Load test data from the JSON file
TEST_DATA_FILENAME = "search_json.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(filepath):
    with open(filepath, 'r') as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"Scenario: {case['scenario']}" for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_search_autocomplete(api_client, config_test_data, scenario_case):
    """
    Test the /v1/search.json endpoint for various scenarios.
    """
    # Merge default test data with scenario specific data
    test_data = {**config_test_data, **scenario_case}
    
    # Assemble request parameters
    params = {}
    if "q" in test_data:
        params["q"] = test_data["q"]

    # Validate request schema
    validator.validate_json(params, "SearchAutocompleteRequest")

    # Send request
    response = api_client.get("v1/search.json", params=params)

    # Assert status code
    assert response.status_code == test_data["statusCode"], f"Unexpected status code: {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        "/v1/search.json", "GET", str(test_data["statusCode"]), response
    )
    assert validation_result["valid"], f"Response validation failed: {validation_result.get('message')}"
