# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /timezone.json_get for http method type GET 
# RoostTestHash=df6b1e5ce9
# 
# 

# ********RoostGPT********
"""
Pytest Test Suite for Time Zone API

This test suite validates the Time Zone API using pytest framework. It covers:
- Endpoint testing for all response status codes.
- Security schema testing for API key authentication.
- Comprehensive request and response validation.

Instructions:
- Ensure `conftest.py` and `validator.py` are in the same directory.
- Update the environment variables for the host and API key.
- Place `timezone_json.json` in the same directory as this test file.

To run the tests:
    pytest <this_file_name>.py
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

HERE = Path(__file__).resolve().parent
TEST_DATA_FILENAME = "timezone_json.json"
API_SPEC_PATH = "api.json"

# Load test data from JSON file
def _load_json_file(filepath):
    with open(filepath, "r") as file:
        return json.load(file)

# Load API specification
swagger_validator = SwaggerSchemaValidator(API_SPEC_PATH)

# Load endpoint test data
_endpoint_data_path = HERE / TEST_DATA_FILENAME
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case["scenario"] for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_time_zone_api(api_client, scenario_case, config_test_data):
    """
    Test the Time Zone API with various scenarios.
    """
    # Configuration
    endpoint = "timezone.json"
    
    # Merge scenario-specific data with default test data
    test_data = {**config_test_data, **scenario_case}
    
    # Prepare request parameters
    params = {}
    if "q" in test_data:
        params["q"] = test_data["q"]

    # Make the API request
    response = api_client.get(endpoint, params=params)

    # Assert the status code
    assert response.status_code == test_data["statusCode"], (
        f"Expected {test_data['statusCode']}, got {response.status_code}"
    )

    # Validate the response schema
    validation_result = swagger_validator.validate_schema_by_response(
        f"/{endpoint}", "GET", str(test_data["statusCode"]), response
    )
    assert validation_result["valid"], (
        f"Schema validation failed: {validation_result.get('message', '')}"
    )
