# ********RoostGPT********

# Test generated by RoostGPT for test tr-api-test-pytest_clone using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /history.json_get for http method type GET 
# RoostTestHash=6ba88fbe10
# 
# 

# ********RoostGPT********
"""
Instructions for running the tests:
- Ensure pytest is installed in your environment.
- Place the following files in the same directory: test_api.py, conftest.py, validator.py, config.yml, history_json.json.
- Run the tests using the command: pytest test_api.py
"""

import pytest
from validator import SwaggerSchemaValidator
from pathlib import Path
import json

# Constants for test data file and OpenAPI spec
TEST_DATA_FILENAME = "history_json.json"
API_SPEC_PATH = "api.json"

# Load JSON test data
def _load_json_file(file_path):
    with open(file_path, 'r') as file:
        return json.load(file)

# Load test data and prepare parameterization
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case['scenario'] for case in _ENDPOINT_DATA]

# Initialize SwaggerSchemaValidator
swagger_validator = SwaggerSchemaValidator(API_SPEC_PATH)

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
@pytest.mark.smoke
def test_get_history_weather_success(api_client, config_test_data, scenario_case):
    """
    Test the /v1/history.json endpoint for valid scenarios.
    """
    endpoint = "v1/history.json"
    
    # Prepare request parameters
    params = {"q": scenario_case.get("q")}
    if "dt" in scenario_case:
        params["dt"] = scenario_case["dt"]
    if "unixdt" in scenario_case:
        params["unixdt"] = scenario_case["unixdt"]
    if "end_dt" in scenario_case:
        params["end_dt"] = scenario_case["end_dt"]
    if "hour" in scenario_case:
        params["hour"] = scenario_case["hour"]
    if "lang" in scenario_case:
        params["lang"] = scenario_case["lang"]
    
    # Validate request schema
    swagger_validator.validate_json(params, "HistoryAPIRequest")

    # Make the API call
    response = api_client.get(endpoint, params=params)
    
    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, "GET", str(scenario_case["statusCode"]), response)
    assert validation_result["valid"], f"Response schema validation failed: {validation_result.get('message')}"

    # Assert status code
    assert response.status_code == scenario_case["statusCode"]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_history_weather_auth_errors(api_client, config_test_data, scenario_case):
    """
    Test the /v1/history.json endpoint for authentication errors.
    """
    endpoint = "v1/history.json"
    
    # Prepare request parameters
    params = {"q": scenario_case.get("q")}
    
    # Test missing API key
    with pytest.raises(RuntimeError, match="Request failed"):
        api_client.session.headers.pop('Authorization', None)
        api_client.get(endpoint, params=params)

    # Test invalid API key
    api_client.session.headers['Authorization'] = "InvalidAPIKey"
    response = api_client.get(endpoint, params=params)
    assert response.status_code == 401

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_history_weather_client_errors(api_client, config_test_data, scenario_case):
    """
    Test the /v1/history.json endpoint for client errors.
    """
    endpoint = "v1/history.json"
    
    # Prepare request parameters
    params = {"q": scenario_case.get("q")}

    # Test with missing 'q' parameter
    if "q" not in params:
        with pytest.raises(RuntimeError, match="Request failed"):
            api_client.get(endpoint, params={})

    # Test with invalid 'q' parameter
    params["q"] = "InvalidLocation"
    response = api_client.get(endpoint, params=params)
    assert response.status_code == 400

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_history_weather_server_errors(api_client, config_test_data, scenario_case):
    """
    Test the /v1/history.json endpoint for server errors.
    """
    endpoint = "v1/history.json"
    
    # Prepare request parameters
    params = {"q": scenario_case.get("q")}
    
    # Simulate server error by using an invalid endpoint
    with pytest.raises(RuntimeError, match="Request failed"):
        api_client.get("v1/invalid_endpoint", params=params)
